version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adoptapp
    container_name: my-mysql-docker-compose
    volumes:
      - mysql-volume:/var/lib/mysql
  my-app-back:
    build: .
    image: my-app:v1
    ports:
      - 8080:8080
    container_name: my-app-docker-compose
    depends_on:
      - db
  my-app-front:
    build:
      context: ../frontend-carpeta/.
      dockerfile: Dockerfile
    image: my-app-frontend:v1
    ports:
        - 5173:5173
    depends_on:
      - my-app-back
    container_name: my-app-frontend-docker-compose



volumes:
  mysql-volume: